### PR TITLE
Hook to allow fields with values other than value to display in form

### PR DESCRIPTION
**Pull request by lifeinpoetry**
This is just a rough idea. Comments would need to be changed and whatever else. It is working on my DrupalGap install though I do create a fake 'value' in the hook for my field in case it's required elsewhere in the module.

### CODE REVIEW

**Comment by signalpoint** [comment]
@GabrielleV will you please elaborate on your field's configuration so I can better understand why this is needed?

AFAIK, this functionality already exists within DrupalGap core, although it isn't well documented and not many know about it. To get a custom value to appear on an entity create/edit form, use this hook:

hook_field_widget_form()

For more advanced fields, I typically switch the actual form input to a hidden field, then use children to build the various input mechanism that control the widget. Then any time one of those inputs has their value changed, I'll update the hidden field, that way the DrupalGap Forms API can pick it up. Examples of this are in the date and geofield modules for DrupalGap.

When it comes time to send field data to the server, that is where hook_assemble_form_state_into_field() comes into play. It allows each field to manually build its JSON before sending it to the server, so the default structure isn't always used:

```
field_my_text: {
  und: [ { value: "Blah blah" } ]
}
```

There is more info about these hooks here:

https://github.com/signalpoint/DrupalGap/blob/7.x-1.x/src/modules/api/api.js

**Comment by signalpoint** [comment]
@GabrielleV Also, will you please paste your example implementation of the hook you have created here? Thanks!

**Comment by lifeinpoetry** [comment]
I am using field_widget_form. The issue was that fields that did not supply 'value' in what was returned from the entity query in json would have nothing to work with. Nothing would be in hook_field_widget_form. 

I changed the name of one function I was using (for Link) and all I end up with in items[delta] in the link_field_widget_form function is:

```
children: Array[0]
length: 0
__proto__: Array[0]
default_value: ""
id: "edit-profile2-edit-field-p2-tumblr-und-0-value"
options: Object
attributes: Object
__proto__: Object
required: 0
title: "Tumblr"
type: "hidden"
value: ""
```

Value and default_value are empty. When I use my code and something like the following:

```
function link_assemble_form_value_into_field(entity_type, bundle,
  entity, field, instance, langcode, delta) {
  try {
    var result = null;

    switch (instance.widget.type) {
      case 'link_field':
        var result = {
           'value': '', 
           'url': entity[langcode][delta].url, 
           'url_title': entity[langcode][delta].title
        };
        break;
    }

    return result;
  }
  catch (error) {
    console.log('link_assemble_form_value_into_field - ' + error);
  }
}
```

then I have values I can work with in  hook_field_widget_form. I've successfully edited links using this method when I was unable to before.

Is there another way I'm unaware of? I posted a topic on Drupal but I see it was closed as a duplicate.

**Comment by signalpoint** [comment]
@GabrielleV thank you, this is looking good. I believe what you have done here is related to this feature in Drupal core:

https://api.drupal.org/api/drupal/developer!topics!forms_api_reference.html/7#value_callback

DrupalGap Forms API does not support the idea of a value_callback yet, and I think what you've implemented is essentially that. Very good.

Will you please post your implementation of link_field_widget_form() ? Once I take a look at that, I'd like to see what it does, and see if I can modify it to handle this scenario. Then we'll look into getting this functionality into core. Thanks!

**Comment by signalpoint** [comment]
@GabrielleV I ran into the need for this on a separate issue, and I believe I've resolved it without the need for an extra hook. See here:

#297 

Now an entity's field item data is available to hook_field_widget_form(). So in our example with the link_field_widget_form(), the items object now contains the necessary data to build the form input properly.

screenshot from 2014-07-10 15 58 17

Grab the latest dev snapshot for the fix: http://drupalgap.org/download

Thanks again for digging into the code to find out the need for this!

**Pull request closed without merging**
