### PR TITLE
7.x 1.x offline

### PR DESCRIPTION
**Pull request by bircher**
small bug fix and allowing ripple to test offline mode.
(note: it just signals the app it is offline, but all requests still go through, but this is an issue in ripple)

### CODE REVIEW

**Comment by signalpoint** [comment]
@bircher Thanks for the pull requests. On a side note, I had to re-enable the Ripple forced "Ethernet connection" value (https://github.com/signalpoint/DrupalGap/commit/aee78b163890506d203cd4fd3636c4a97212b520), otherwise I'm not available to get any connection to respond in Ripple (Ubuntu 12.04). I'm not sure what's up with that, feel free to add any additional info if you know why, otherwise we'll just leave that snippet alone for now.

**Comment by bircher** [comment]
which version of ripple are you using?
I am using 0.9.22
(which supports cordova 3)

**Comment by signalpoint** [comment]
@bircher I'm running 0.9.15, which appears to be the latest available through the Chrome plugin manager. I'm guessing you obtained 0.9.22 through npm?

**Comment by bircher** [comment]
Yes, I got it through npm because the chrome plugin didn't support cordova 3 apps and I read somewhere that the chrome plugin is discontinued in favor of the command line tool. But I might be wrong on this.

**Pull request merged**
