### PR TITLE
Added possibility to populate a table that has been created using the th...

### PR DESCRIPTION
**Pull request by quiquee**
...eme:table and then use

the drupalgap_table_populate , similar to what drupalgap_item_list populate does

### CODE REVIEW

**Comment by signalpoint** [comment]
@quiquee Thanks, I've merged in these changes. Please consider pasting your example usage of this code in a comment here, or add it to the Getting Started Guide Tables page:

http://drupalgap.org/node/188

**Comment by quiquee** [comment]
Will do thanks. Regarding styling,  what are u our preferences? I have some
css to beautify the table but I am unsure if this is something you want
contributions
Thank you

**Comment by signalpoint** [comment]
@quiquee Let's just leave it as plain as possible, and let each app set up their table css needs.

I just made the theme_jqm_table() function which will let us do theme('jqm_table', {blah}); to get some out-of-the-box styling:

https://github.com/signalpoint/DrupalGap/commit/4130da0d04f4408f072bbee2109c459a208122c2

**Comment by quiquee** [comment]
Understood
Thanks

**Comment by quiquee** [comment]
Hello Tyler,
one thing, i was going to update the doc on the tables theme following what
was in lists as example and I realised that
the drupalgap_item_list_populate is not documented there, but in the views
via pageshow section. Hence, documenting it in the table specifc section
will not be consistent. I propose to add it to the documentation of the
list ( a link to the views example that shows usage of
drupalgap_item_list_populate) . I will then add the example on
drupalgap_item_table_populate to the table section of the doc. I hope it is
clear.
Regards and thanks

On Wed, Apr 2, 2014 at 5:50 AM, Tyler Frankenstein <notifications@github.com

**Comment by signalpoint** [comment]
@quiquee Feel free to add it in the documentation anywhere you like. I receive notifications any time there are changes to it, so if something needs to be moved around at a later time, it isn't a problem. Thanks!

**Pull request merged**
