### PR TITLE
added function drupalgap_file_exist and some changes to drupalgap_settin...

### PR DESCRIPTION
**Pull request by uniquename**
...gs_load

not sure if it should go into this branch. I saw you added include files in the theme branch and i thought drupalgap_file_exists should probably live in such an include file.

### CODE REVIEW

**Comment by uniquename** [comment]
i also added a function drupalgap_alert, it just wraps navigator.notification.alert. My intention here is to have functions like drupalgap_settings_load most easy to read.

**Comment by uniquename** [comment]
...being kind of new to work with github, I didn't know that a pull request is per branch an not per commit... I can fiddle that apart, if you don't like one of the commits

**Comment by signalpoint** [comment]
Thank you uniquename! This all looks good. It is OK to put the pull request on the 7.x-1.x branch. I am off on two unstable branches right now (-dev and -dev-theme), and once I wrap those up I'll be pulling them back into the 7.x-1.x branch.

Great idea with the drupalgap alert, I've wanted to do that for a while now. Once I got these other two branches merged in, we can migrate your changes into one of the include files.

**Comment by uniquename** [comment]
yap, i saw your work on -dev-theme, looks quite promising. I also thinking about that for a while and always end up considering mustache/handlebars and jed. what's your opinion/plan about something like that?

**Comment by signalpoint** [comment]
Well right now I have a beard. Haha. Ok, I looked up mustache handlebars js. Wow, looks awesome. I'd love if we could have syntax like that. I don't know enough (anything) about using it though, so I'm not sure if we'd want to bring in another library. It is important to consider though, I haven't gotten to deep into the placeholder replacement yet, I'm still battling with dynamic page creation (so the back button works properly).

**Comment by signalpoint** [comment]
Thanks for this pull request. Sorry I wasn't able to merge it in cleanly, I was off on the Alpha branch and instead just brought your code in manually for the drupalgap_file_exists() function here:

https://github.com/signalpoint/DrupalGap/blob/7.x-1.x-alpha/drupalgap.js#L345

Since my last comment here, much has changed with DrupalGap. All the work mentioned on the *-dev-theme branch  is now inside the Alpha branch. There have been many great changes, so please check them out and let me know what you think.

I still would like to get your drupalgap_alert() function into Alpha as well, please create a separate pull request if you have time to implement it, thanks!

**Comment by uniquename** [comment]
Hi Tyler,
I was off for some other coding ...just came back here and wanted to keep your pull request queue clean ;-) 

Nice that my function made it in!

I will have to look at all the changes and at drupalgap_alert... it's been a while...

**Pull request closed without merging**
